const messages = {
    zh: {
        common: {
            t1: '我的',
            t2: "语言切换",
            t3: "智能合约地址",
            t4: "合约资金池",
            t5: "总投资金额",
            t6: "TRON区块",
            t7: "合约代码",
            t8: "查看 TRONSCAN",
            t9: "加入等级 TRX",
            t10: "立即参与",
            t11: "项目介绍",
            t12: "温馨提示",
            t13: "您有一笔资金出局，是否签名提币？",
            t14: "再等等",
            t15: "马上提币",
            t16: "TRON时间戳的智能合约投顾平台",
            t17: "合约执行",
            t18: "开源审计",
            t19: "无法篡改",
            t20: "开源",
            t21: "链上运行",
            t22: "无法篡改",
            t23: "G-Voyage是最安全、最活跃的TRON区块链智能合约平台。可信的时间戳，100%的透明度，任何人都不能更改其规则或进程，任何人都可以检查开源的代码。",
            t24: "开放条件",
            t25: "早期3k，9k，18k，30k，45k TRX是被允许的，后每864000波场区块高度开放一新级别。",
            t26: "参与条件",
            t27: "最低存款：3000 TRX",
            t28: "总收入：每次获得230%收益",
            t29: "提现：秒到钱包 (7*24h）",
            t30: "多重收益",
            t31: "优先奖励",
            t32: "新周期发射时，50个优先用户参与合约池2.5%奖励",
            t33: "持有利润",
            t34: "0.1%—2.5%每28800区块，0.1%递增当没提现时",
            t35: "分享利润",
            t36: "每完成一次分享会激活60%的利润分配",
            t037: "支持收益",
            t37: "6%分配给与你直接相连的20个早期用户",
            t38: "100用户加权分配当合约池/总投资≤2%，开启2.0阶段",
            t39: "G-Voyage唯一通证GV奖励给持有利润和分享利润",
            t40: "了解更多",
            t41: "审计公司：",
            t42: "审计公司",
            t43: "审计报告结论",
            t44: "成功通过",
            t45: "合约审计报告",
            t46: "联系我们",
            t47: "基于TRON时间戳的智能合约投顾平台",
            img1: "js/langImg/zh/2.png",
            img2: "js/langImg/zh/1.png",
            img3: "js/langImg/zh/3.png",


        }
    },
    en: {
        common: {
            t1: 'Mine',
            t2: "Language Switch",
            t3: "Smart Contract Address",
            t4: "Contract Fund Pool",
            t5: "Total Investment Amount",
            t6: "TRON Block",
            t7: "Contract Code",
            t8: "View TRONSCAN",
            t9: "Join level TRX",
            t10: "Participate now",
            t11: "Project Introduction",
            t12: "Warm Reminder",
            t13: "You have a fund out, do you want to sign the withdrawal?",
            t14: "Wait again",
            t15: "Withdraw coins now",
            t16: "TRON timestamp smart contract investment advisory platform",
            t17: "Contract Execution",
            t18: "Open Source Audit",
            t19: "Cannot be tampered with",
            t20: "Contract",
            t21: "Audit",
            t22: "Unchange",
            t23: "G-Voyage is the safest and most active TRON blockchain smart contract platform. Trusted timestamp, 100% transparency, no one can change its rules or processes, anyone can check the open source code .",
            t24: "Open Conditions",
            t25: "In the early period 3000, 9000, 18000, 30000, 45000 TRX are allowed, and a new level will be opened every 86400 block height.",
            t26: "Participation Conditions",
            t27: "Minimum Deposit: 3000 TRX",
            t28: "Total income: 230% income each time",
            t29: "Withdrawal: to wallet in seconds(7*24h）",
            t30: "Multiple benefits",
            t31: "Priority Award",
            t32: "When the new cycle is launched, 50 priority users participate in the contract pool 2.5% reward",
            t33: "Holding Profit",
            t34: "0.1%—2.5% every 28800 blocks, 0.1% increments when there is no withdrawal",
            t35: "Share Profit",
            t36: "Each share will activate 60% of the profit distribution",
            t037: "Support Income",
            t37: "6% is allocated to 20 early users directly connected to you",
            t38: "100 user weighted allocation when contract pool/total investment ≤2%, start 2.0 phase",
            t39: "Among them, G-Voyage's only ecological token, GV, rewards  for holding profits and sharing profits",
            t40: "Learn more",
            t41: "Audit Company:",
            t42: "Audit Company",
            t43: "Audit Report Conclusion",
            t44: "Passed successfully",
            t45: "Contract Audit Report",
            t46: "Contact Us",
            t47: "Smart contract investment advisory platform based on TRON timestamp",
            img1: "js/langImg/en/2.png",
            img2: "js/langImg/en/3.png",
            img3: "js/langImg/en/1.png",
        }
    },
    /*俄国*/
    es: {
        common: {
            t1: "шахта",
            t2: "Переключение языка",
            t3: "Адрес смарт-контракта",
            t4: "Пул контрактного фонда",
            t5: "Общая сумма инвестиций",
            t6: "Блок ТРОН",
            t7: "Код контракта",
            t8: "Просмотреть TRONSCAN",
            t9: "Уровень присоединения TRX",
            t10: "Участвуйте сейчас",
            t11: "Введение в проект",
            t12: "Теплое напоминание",
            t13: "У вас есть средства, вы хотите подписать вывод?",
            t14: "Подожди еще раз",
            t15: "Снять монеты сейчас",
            t16: "Платформа инвестиционного консалтинга для смарт-контрактов TRON",
            t17: "Исполнение контракта",
            t18: "Аудит открытого исходного кода",
            t19: "Невозможно подделать",
            t20: "Открытый исходный код",
            t21: "Запуск по цепочке",
            t22: "Невозможно подделать",
            t23: "G-Voyage - самая безопасная и самая активная платформа смарт-контрактов на блокчейне TRON. Надежная временная метка, 100% прозрачность, никто не может изменять ее правила или процессы, любой может проверить открытый исходный код. . ",
            t24: "Открытые условия",
            t25: "В ранний период разрешены 3000, 9000, 18000, 30000, 45000 TRX, и новый уровень будет открываться через каждые 86400 блоков высоты.",
            t26: "Условия участия",
            t27: "Минимальный депозит: 3000 TRX",
            t28: "Общий доход: 230% дохода каждый раз",
            t29: "Вывод: на кошелек за секунды(7*24h）",
            t30: "Множественная выгода",
            t31: "Приз за приоритет",
            t32: "50 приоритетных пользователей участвуют в пуле контрактов 2,5% вознаграждения",
            t33: "Холдинговая прибыль",
            t34: "0,1% —2,5% через каждые 28800 блоков, с шагом 0,1%, когда нет вывода",
            t35: "Доля прибыли",
            t36: "Каждая акция активирует 60% распределения прибыли",
            t037: "ожидать",
            t37: "6% выделяется 20 ранним пользователям, напрямую подключенным к вам",
            t38: "Взвешенное распределение 100 пользователей при пуле контрактов / общих инвестициях ≤ 2%",
            t39: "Среди них единственный экологический токен G-Voyage, GV, вознаграждает за удержание прибыли и распределение прибыли",
            t40: "Узнать больше",
            t41: "Аудиторская компания:",
            t42: "Компания",
            t43: "Заключение аудиторского отчета",
            t44: "Успешно пройдено",
            t45: "Отчет об аудите контракта",
            t46: "Свяжитесь с нами",
            t47: "Платформа инвестиционного консультирования по смарт-контрактам на основе временной метки TRON",
            img1: "js/langImg/es/1.png",
            img2: "js/langImg/es/2.png",
            img3: "js/langImg/es/3.png",
        }
    },
    /*韩国*/
    ru: {
        common: {
            t1: '개인 센터',
            t2: "언어 전환",
            t3: "스마트 계약 주소",
            t4: "계약 자금 풀",
            t5: "총 투자 금액",
            t6: "TRON 블록",
            t7: "계약 코드",
            t8: "트론 스캔보기",
            t9: "레벨 가입 TRX",
            t10: "지금 참여하세요",
            t11: "프로젝트 소개",
            t12: "따뜻한 알림",
            t13: "자금이 있습니다. 출금에 서명 하시겠습니까?",
            t14: "다시 기다리십시오",
            t15: "지금 코인 인출",
            t16: "TRON 타임 스탬프 스마트 계약 투자 자문 플랫폼",
            t17: "계약 실행",
            t18: "오픈 소스 감사",
            t19: "변경할 수 없음",
            t20: "오픈 소스",
            t21: "체인에서 실행",
            t22: "조작 할 수 없음",
            t23: "G-Voyage는 가장 안전하고 가장 활동적인 TRON 블록 체인 스마트 계약 플랫폼입니다. 신뢰할 수있는 타임 스탬프, 100 % 투명성, 누구도 규칙이나 프로세스를 변경할 수 없으며 누구나 오픈 소스 코드를 확인할 수 있습니다. . ",
            t24: "개방 조건",
            t25: "초기에는 3000, 9000, 18000, 30000, 45000 TRX가 허용되며 86400 블록 높이마다 새 레벨이 열립니다.",
            t26: "참여 조건",
            t27: "최소 예치금 : 3000 TRX",
            t28: "총소득 : 매번 230 % 소득",
            t29: "출금 : 몇 초 만에 지갑으로(7*24h）",
            t30: "다양한 혜택",
            t31: "우선권 상",
            t32: "새로운주기가 시작되면 50 명의 우선 순위 사용자가 계약 풀에 참여하여 2.5 % 보상",
            t33: "지주 이익",
            t34: "0.1 % —2.5 % 매 28800 블록, 인출이 없을 때 0.1 % 증가",
            t35: "이익 공유",
            t36: "각 주식은 수익 분배의 60 %를 활성화합니다.",
            t037: "지원 소득",
            t37: "6 %는 귀하와 직접 연결된 초기 사용자 20 명에게 할당됩니다.",
            t38: "계약 풀 / 총 투자 ≤2 %, 2.0 단계 시작시 100 명의 사용자 가중치 할당",
            t39: "그중에서 G-Voyage의 유일한 생태 토큰 인 GV는 이익 보유 및 이익 공유에 대해 13 % 보상",
            t40: "자세히 알아보기",
            t41: "감사 회사 :",
            t42 : "감사 회사",
            t43: "감사 보고서 결론",
            t44: "성공적으로 통과",
            t45: "계약 감사 보고서",
            t46: "문의하기",
            t47: "TRON 타임 스탬프 기반 스마트 계약 투자 자문 플랫폼",
            img1: "js/langImg/ru/1.png",
            img2: "js/langImg/ru/2.png",
            img3: "js/langImg/ru/3.png",
        }
    }
}

